# Generated by Django 5.2.12 on 2026-03-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtrack', '0002_expense_expensenotification_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AddField(
            model_name='expense',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
