# Generated by Django 5.2.12 on 2026-03-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtrack', '0004_userprofile_budget_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensenotification',
            name='notification_type',
            field=models.CharField(choices=[('daily', 'Daily Reminder'), ('overspend', 'Overspend Alert'), ('monthly_insight', 'Monthly Insight')], max_length=20),
        ),
    ]
